"""Tiered rankings + risk-flag dataset, and season playbook rules.

Ported from the standalone draft-board artifact (see
reference/draft-board.html in this repo). Update tiers/flags/ADP by hand
as news breaks - there is no external rankings feed wired in yet.

adp_pick_overall/adp_round/adp_slot/delta_flag/is_rookie/note fields were
merged in 2026-07 from 4for4 consensus ADP (10-team PPR, pulled 2026-07-09)
to compare hand-curated tiers against where players are actually being
drafted. Not every player has these fields - only those covered by that
pull. delta_flag values: "riser", "faller", "confirmed", "as_expected".
"""

PLAYERS: list = [
    {"rank": 1, "name": 'Jahmyr Gibbs', "pos": 'RB', "team": 'DET', "tier": 1, "flags": [], "target": True, "watch": False, "adp_pick_overall": 1, "adp_round": 1, "adp_slot": 1, "delta_flag": 'as_expected', "is_rookie": False},
    {"rank": 2, "name": 'Bijan Robinson', "pos": 'RB', "team": 'ATL', "tier": 1, "flags": [], "target": True, "watch": False, "adp_pick_overall": 2, "adp_round": 1, "adp_slot": 2, "delta_flag": 'as_expected', "is_rookie": False},
    {"rank": 3, "name": 'Christian McCaffrey', "pos": 'RB', "team": 'SF', "tier": 1, "flags": ['injury'], "target": True, "watch": False, "adp_pick_overall": 6, "adp_round": 1, "adp_slot": 6, "delta_flag": 'as_expected', "is_rookie": False},
    {"rank": 4, "name": "Ja'Marr Chase", "pos": 'WR', "team": 'CIN', "tier": 1, "flags": [], "target": True, "watch": False, "adp_pick_overall": 3, "adp_round": 1, "adp_slot": 3, "delta_flag": 'as_expected', "is_rookie": False},
    {"rank": 5, "name": 'Puka Nacua', "pos": 'WR', "team": 'LAR', "tier": 1, "flags": [], "target": False, "watch": False, "adp_pick_overall": 4, "adp_round": 1, "adp_slot": 4, "delta_flag": 'as_expected', "is_rookie": False},
    {"rank": 6, "name": 'Justin Jefferson', "pos": 'WR', "team": 'MIN', "tier": 1, "flags": ['scheme'], "target": False, "watch": True, "adp_pick_overall": 11, "adp_round": 2, "adp_slot": 1, "delta_flag": 'as_expected', "is_rookie": False},
    {"rank": 7, "name": 'CeeDee Lamb', "pos": 'WR', "team": 'DAL', "tier": 1, "flags": ['injury'], "target": False, "watch": False},
    {"rank": 8, "name": 'Amon-Ra St. Brown', "pos": 'WR', "team": 'DET', "tier": 1, "flags": [], "target": True, "watch": False, "adp_pick_overall": 7, "adp_round": 1, "adp_slot": 7, "delta_flag": 'as_expected', "is_rookie": False},
    {"rank": 9, "name": 'Jonathan Taylor', "pos": 'RB', "team": 'IND', "tier": 1, "flags": [], "target": False, "watch": False, "adp_pick_overall": 8, "adp_round": 1, "adp_slot": 8, "delta_flag": 'as_expected', "is_rookie": False},
    {"rank": 10, "name": 'Saquon Barkley', "pos": 'RB', "team": 'PHI', "tier": 1, "flags": [], "target": False, "watch": False, "adp_pick_overall": 14, "adp_round": 2, "adp_slot": 4, "delta_flag": 'faller', "is_rookie": False},
    {"rank": 11, "name": 'Jaxon Smith-Njigba', "pos": 'WR', "team": 'SEA', "tier": 2, "flags": [], "target": False, "watch": False, "adp_pick_overall": 5, "adp_round": 1, "adp_slot": 5, "delta_flag": 'as_expected', "is_rookie": False},
    {"rank": 12, "name": 'Malik Nabers', "pos": 'WR', "team": 'NYG', "tier": 3, "flags": ['injury'], "target": False, "watch": False, "adp_pick_overall": 32, "adp_round": 4, "adp_slot": 2, "delta_flag": 'as_expected', "is_rookie": False, "note": "Market hasn't priced in the ACL concern as much as you have"},
    {"rank": 13, "name": 'Nico Collins', "pos": 'WR', "team": 'HOU', "tier": 2, "flags": ['injury'], "target": False, "watch": False},
    {"rank": 14, "name": "De'Von Achane", "pos": 'RB', "team": 'MIA', "tier": 2, "flags": ['scheme'], "target": False, "watch": False, "adp_pick_overall": 13, "adp_round": 2, "adp_slot": 3, "delta_flag": 'riser', "is_rookie": False},
    {"rank": 15, "name": 'Ashton Jeanty', "pos": 'RB', "team": 'LV', "tier": 2, "flags": [], "target": False, "watch": False, "adp_pick_overall": 10, "adp_round": 1, "adp_slot": 10, "delta_flag": 'riser', "is_rookie": False},
    {"rank": 16, "name": 'Brian Thomas Jr.', "pos": 'WR', "team": 'JAX', "tier": 2, "flags": [], "target": False, "watch": False, "adp_pick_overall": 68, "adp_round": 7, "adp_slot": 8, "delta_flag": 'faller', "is_rookie": False},
    {"rank": 17, "name": 'Derrick Henry', "pos": 'RB', "team": 'BAL', "tier": 2, "flags": [], "target": True, "watch": False, "adp_pick_overall": 20, "adp_round": 2, "adp_slot": 10, "delta_flag": 'as_expected', "is_rookie": False},
    {"rank": 18, "name": 'Josh Jacobs', "pos": 'RB', "team": 'GB', "tier": 2, "flags": [], "target": False, "watch": False, "adp_pick_overall": 36, "adp_round": 4, "adp_slot": 6, "delta_flag": 'faller', "is_rookie": False, "note": 'Legal risk elevated - May 2026 arrest on domestic-abuse charges'},
    {"rank": 19, "name": 'Chase Brown', "pos": 'RB', "team": 'CIN', "tier": 2, "flags": [], "target": True, "watch": False, "adp_pick_overall": 16, "adp_round": 2, "adp_slot": 6, "delta_flag": 'as_expected', "is_rookie": False},
    {"rank": 20, "name": 'A.J. Brown', "pos": 'WR', "team": 'NE', "tier": 2, "flags": ['scheme'], "target": True, "watch": False},
    {"rank": 21, "name": 'Drake London', "pos": 'WR', "team": 'ATL', "tier": 3, "flags": [], "target": False, "watch": False},
    {"rank": 22, "name": 'Tee Higgins', "pos": 'WR', "team": 'CIN', "tier": 3, "flags": [], "target": True, "watch": False},
    {"rank": 23, "name": 'Trey McBride', "pos": 'TE', "team": 'ARI', "tier": 3, "flags": [], "target": False, "watch": False},
    {"rank": 24, "name": 'Brock Bowers', "pos": 'TE', "team": 'LV', "tier": 3, "flags": ['injury'], "target": False, "watch": False},
    {"rank": 25, "name": 'Ladd McConkey', "pos": 'WR', "team": 'LAC', "tier": 3, "flags": [], "target": False, "watch": False, "adp_pick_overall": 42, "adp_round": 5, "adp_slot": 2, "delta_flag": 'confirmed', "is_rookie": False},
    {"rank": 26, "name": 'Terry McLaurin', "pos": 'WR', "team": 'WSH', "tier": 3, "flags": [], "target": False, "watch": False, "adp_pick_overall": 44, "adp_round": 5, "adp_slot": 4, "delta_flag": 'as_expected', "is_rookie": False},
    {"rank": 27, "name": 'DK Metcalf', "pos": 'WR', "team": 'PIT', "tier": 3, "flags": ['scheme'], "target": False, "watch": False, "adp_pick_overall": 74, "adp_round": 8, "adp_slot": 4, "delta_flag": 'as_expected', "is_rookie": False},
    {"rank": 28, "name": 'Garrett Wilson', "pos": 'WR', "team": 'NYJ', "tier": 3, "flags": ['injury'], "target": False, "watch": False},
    {"rank": 29, "name": 'Bucky Irving', "pos": 'RB', "team": 'TB', "tier": 3, "flags": ['committee'], "target": False, "watch": False, "adp_pick_overall": 55, "adp_round": 6, "adp_slot": 5, "delta_flag": 'faller', "is_rookie": False},
    {"rank": 30, "name": 'James Cook', "pos": 'RB', "team": 'BUF', "tier": 3, "flags": [], "target": False, "watch": False, "adp_pick_overall": 12, "adp_round": 2, "adp_slot": 2, "delta_flag": 'confirmed', "is_rookie": False},
    {"rank": 31, "name": 'Josh Allen', "pos": 'QB', "team": 'BUF', "tier": 3, "flags": [], "target": False, "watch": False},
    {"rank": 32, "name": 'Lamar Jackson', "pos": 'QB', "team": 'BAL', "tier": 3, "flags": [], "target": False, "watch": False},
    {"rank": 33, "name": 'Jayden Daniels', "pos": 'QB', "team": 'WSH', "tier": 3, "flags": ['injury'], "target": False, "watch": False},
    {"rank": 34, "name": 'Joe Burrow', "pos": 'QB', "team": 'CIN', "tier": 3, "flags": [], "target": False, "watch": False},
    {"rank": 35, "name": 'Omarion Hampton', "pos": 'RB', "team": 'LAC', "tier": 3, "flags": ['injury', 'breakout'], "target": True, "watch": False},
    {"rank": 36, "name": 'Kenneth Walker III', "pos": 'RB', "team": 'KC', "tier": 2, "flags": [], "target": False, "watch": False, "adp_pick_overall": 19, "adp_round": 2, "adp_slot": 9, "delta_flag": 'as_expected', "is_rookie": False, "note": 'Signed with Chiefs in free agency after Super Bowl MVP run with Seattle'},
    {"rank": 37, "name": 'Travis Etienne Jr.', "pos": 'RB', "team": 'NO', "tier": 4, "flags": [], "target": False, "watch": False, "adp_pick_overall": 33, "adp_round": 4, "adp_slot": 3, "delta_flag": 'as_expected', "is_rookie": False, "note": 'Traded to New Orleans this offseason'},
    {"rank": 38, "name": 'James Conner', "pos": 'RB', "team": 'ARI', "tier": 4, "flags": [], "target": False, "watch": False},
    {"rank": 39, "name": 'Chuba Hubbard', "pos": 'RB', "team": 'CAR', "tier": 4, "flags": [], "target": False, "watch": False, "adp_pick_overall": 72, "adp_round": 8, "adp_slot": 2, "delta_flag": 'confirmed', "is_rookie": False},
    {"rank": 40, "name": 'Alvin Kamara', "pos": 'RB', "team": 'NO', "tier": 4, "flags": [], "target": False, "watch": False},
    {"rank": 41, "name": 'Kyren Williams', "pos": 'RB', "team": 'LAR', "tier": 4, "flags": [], "target": False, "watch": False, "adp_pick_overall": 31, "adp_round": 4, "adp_slot": 1, "delta_flag": 'faller', "is_rookie": False},
    {"rank": 42, "name": 'Breece Hall', "pos": 'RB', "team": 'NYJ', "tier": 4, "flags": [], "target": False, "watch": False},
    {"rank": 43, "name": 'Tony Pollard', "pos": 'RB', "team": 'TEN', "tier": 4, "flags": [], "target": False, "watch": False, "adp_pick_overall": 73, "adp_round": 8, "adp_slot": 3, "delta_flag": 'confirmed', "is_rookie": False},
    {"rank": 44, "name": 'David Montgomery', "pos": 'RB', "team": 'HOU', "tier": 4, "flags": [], "target": False, "watch": False, "adp_pick_overall": 52, "adp_round": 6, "adp_slot": 2, "delta_flag": 'as_expected', "is_rookie": False, "note": 'Traded from Detroit to Houston this offseason'},
    {"rank": 45, "name": 'Rachaad White', "pos": 'RB', "team": 'WSH', "tier": 4, "flags": [], "target": False, "watch": False, "adp_pick_overall": 101, "adp_round": 11, "adp_slot": 1, "delta_flag": 'confirmed', "is_rookie": False, "note": 'Signed with Washington this offseason'},
    {"rank": 46, "name": 'Davante Adams', "pos": 'WR', "team": 'LAR', "tier": 4, "flags": [], "target": False, "watch": False},
    {"rank": 47, "name": 'Xavier Worthy', "pos": 'WR', "team": 'KC', "tier": 4, "flags": ['committee'], "target": False, "watch": False},
    {"rank": 48, "name": 'Zay Flowers', "pos": 'WR', "team": 'BAL', "tier": 4, "flags": ['breakout'], "target": False, "watch": False},
    {"rank": 49, "name": 'Jameson Williams', "pos": 'WR', "team": 'DET', "tier": 4, "flags": [], "target": False, "watch": False},
    {"rank": 50, "name": 'Courtland Sutton', "pos": 'WR', "team": 'DEN', "tier": 4, "flags": ['scheme'], "target": False, "watch": False, "adp_pick_overall": 78, "adp_round": 8, "adp_slot": 8, "delta_flag": 'faller', "is_rookie": False},
    {"rank": 51, "name": 'Jaylen Waddle', "pos": 'WR', "team": 'DEN', "tier": 4, "flags": [], "target": False, "watch": False, "adp_pick_overall": 45, "adp_round": 5, "adp_slot": 5, "delta_flag": 'riser', "is_rookie": False, "note": 'Traded to Denver this offseason'},
    {"rank": 52, "name": 'Tetairoa McMillan', "pos": 'WR', "team": 'CAR', "tier": 4, "flags": ['rookie'], "target": False, "watch": False, "adp_pick_overall": 39, "adp_round": 4, "adp_slot": 9, "delta_flag": 'confirmed', "is_rookie": False},
    {"rank": 53, "name": 'Patrick Mahomes', "pos": 'QB', "team": 'KC', "tier": 4, "flags": ['injury'], "target": False, "watch": False},
    {"rank": 54, "name": 'Jalen Hurts', "pos": 'QB', "team": 'PHI', "tier": 3, "flags": [], "target": False, "watch": False},
    {"rank": 55, "name": 'Justin Herbert', "pos": 'QB', "team": 'LAC', "tier": 4, "flags": [], "target": False, "watch": False},
    {"rank": 56, "name": 'George Kittle', "pos": 'TE', "team": 'SF', "tier": 4, "flags": ['injury'], "target": False, "watch": False},
    {"rank": 57, "name": 'Sam LaPorta', "pos": 'TE', "team": 'DET', "tier": 4, "flags": ['injury'], "target": False, "watch": False},
    {"rank": 58, "name": 'Tucker Kraft', "pos": 'TE', "team": 'GB', "tier": 4, "flags": ['breakout', 'injury'], "target": False, "watch": False},
    {"rank": 59, "name": 'Jerry Jeudy', "pos": 'WR', "team": 'CLE', "tier": 5, "flags": [], "target": False, "watch": False, "adp_pick_overall": 163, "adp_round": 17, "adp_slot": 3, "delta_flag": 'confirmed', "is_rookie": False},
    {"rank": 60, "name": 'Rome Odunze', "pos": 'WR', "team": 'CHI', "tier": 5, "flags": ['breakout'], "target": False, "watch": False, "adp_pick_overall": 61, "adp_round": 7, "adp_slot": 1, "delta_flag": 'faller', "is_rookie": False},
    {"rank": 61, "name": 'DeVonta Smith', "pos": 'WR', "team": 'PHI', "tier": 5, "flags": [], "target": False, "watch": False},
    {"rank": 62, "name": 'Christian Watson', "pos": 'WR', "team": 'GB', "tier": 5, "flags": ['breakout'], "target": False, "watch": False, "adp_pick_overall": 62, "adp_round": 7, "adp_slot": 2, "delta_flag": 'faller', "is_rookie": False},
    {"rank": 63, "name": 'Jayden Higgins', "pos": 'WR', "team": 'HOU', "tier": 5, "flags": ['breakout'], "target": False, "watch": False},
    {"rank": 64, "name": 'Michael Pittman Jr.', "pos": 'WR', "team": 'PIT', "tier": 5, "flags": [], "target": False, "watch": False, "adp_pick_overall": 91, "adp_round": 10, "adp_slot": 1, "delta_flag": 'confirmed', "is_rookie": False, "note": 'Traded to Pittsburgh this offseason'},
    {"rank": 65, "name": 'Calvin Ridley', "pos": 'WR', "team": 'TEN', "tier": 5, "flags": [], "target": False, "watch": False, "adp_pick_overall": 169, "adp_round": 17, "adp_slot": 9, "delta_flag": 'confirmed', "is_rookie": False},
    {"rank": 66, "name": 'Keon Coleman', "pos": 'WR', "team": 'BUF', "tier": 5, "flags": [], "target": False, "watch": False},
    {"rank": 67, "name": 'Stefon Diggs', "pos": 'WR', "team": 'FA', "tier": 6, "flags": ['scheme'], "target": False, "watch": False},
    {"rank": 68, "name": 'Deebo Samuel', "pos": 'WR', "team": 'WSH', "tier": 5, "flags": [], "target": False, "watch": False},
    {"rank": 69, "name": 'Chris Olave', "pos": 'WR', "team": 'NO', "tier": 5, "flags": [], "target": False, "watch": False},
    {"rank": 70, "name": 'Jordyn Tyson', "pos": 'WR', "team": 'ARI', "tier": 5, "flags": ['rookie', 'breakout'], "target": False, "watch": False},
    {"rank": 71, "name": 'Luther Burden III', "pos": 'WR', "team": 'CHI', "tier": 5, "flags": ['rookie', 'breakout'], "target": False, "watch": False},
    {"rank": 72, "name": 'Marvin Harrison Jr.', "pos": 'WR', "team": 'ARI', "tier": 5, "flags": [], "target": False, "watch": False, "adp_pick_overall": 66, "adp_round": 7, "adp_slot": 6, "delta_flag": 'confirmed', "is_rookie": False},
    {"rank": 73, "name": 'Rashee Rice', "pos": 'WR', "team": 'KC', "tier": 5, "flags": [], "target": True, "watch": False},
    {"rank": 74, "name": 'Cooper Kupp', "pos": 'WR', "team": 'SEA', "tier": 5, "flags": [], "target": False, "watch": False},
    {"rank": 75, "name": 'George Pickens', "pos": 'WR', "team": 'DAL', "tier": 5, "flags": [], "target": False, "watch": False},
    {"rank": 76, "name": 'Jakobi Meyers', "pos": 'WR', "team": 'JAX', "tier": 5, "flags": [], "target": False, "watch": False, "adp_pick_overall": 105, "adp_round": 11, "adp_slot": 5, "delta_flag": 'faller', "is_rookie": False},
    {"rank": 77, "name": 'Travis Hunter', "pos": 'WR', "team": 'JAX', "tier": 5, "flags": ['rookie'], "target": False, "watch": False},
    {"rank": 78, "name": 'Ricky Pearsall', "pos": 'WR', "team": 'SF', "tier": 5, "flags": [], "target": False, "watch": False, "adp_pick_overall": 103, "adp_round": 11, "adp_slot": 3, "delta_flag": 'confirmed', "is_rookie": False},
    {"rank": 79, "name": 'Bhayshul Tuten', "pos": 'RB', "team": 'JAX', "tier": 4, "flags": ['breakout'], "target": False, "watch": False},
    {"rank": 80, "name": 'Quinshon Judkins', "pos": 'RB', "team": 'CLE', "tier": 5, "flags": [], "target": False, "watch": False, "adp_pick_overall": 51, "adp_round": 6, "adp_slot": 1, "delta_flag": 'faller', "is_rookie": False},
    {"rank": 81, "name": 'Jaylen Warren', "pos": 'RB', "team": 'PIT', "tier": 5, "flags": [], "target": False, "watch": False, "adp_pick_overall": 69, "adp_round": 7, "adp_slot": 9, "delta_flag": 'as_expected', "is_rookie": False},
    {"rank": 82, "name": 'Aaron Jones Sr.', "pos": 'RB', "team": 'MIN', "tier": 5, "flags": [], "target": False, "watch": False, "adp_pick_overall": 112, "adp_round": 12, "adp_slot": 2, "delta_flag": 'confirmed', "is_rookie": False},
    {"rank": 83, "name": 'Rico Dowdle', "pos": 'RB', "team": 'CAR', "tier": 5, "flags": ['committee'], "target": False, "watch": False},
    {"rank": 84, "name": 'Tyrone Tracy Jr.', "pos": 'RB', "team": 'NYG', "tier": 5, "flags": ['committee'], "target": False, "watch": False},
    {"rank": 85, "name": 'Isiah Pacheco', "pos": 'RB', "team": 'DET', "tier": 6, "flags": ['committee', 'injury'], "target": False, "watch": False},
    {"rank": 86, "name": "D'Andre Swift", "pos": 'RB', "team": 'CHI', "tier": 5, "flags": [], "target": False, "watch": False, "adp_pick_overall": 50, "adp_round": 5, "adp_slot": 10, "delta_flag": 'riser', "is_rookie": False},
    {"rank": 87, "name": 'Jerome Ford', "pos": 'RB', "team": 'CLE', "tier": 6, "flags": ['committee'], "target": False, "watch": False},
    {"rank": 88, "name": 'Kenneth Gainwell', "pos": 'RB', "team": 'TB', "tier": 6, "flags": ['breakout', 'committee'], "target": False, "watch": False, "adp_pick_overall": 93, "adp_round": 10, "adp_slot": 3, "delta_flag": 'confirmed', "is_rookie": False},
    {"rank": 89, "name": 'Jonathon Brooks', "pos": 'RB', "team": 'CAR', "tier": 6, "flags": ['injury', 'breakout'], "target": False, "watch": False},
    {"rank": 90, "name": 'Kyler Murray', "pos": 'QB', "team": 'MIN', "tier": 6, "flags": [], "target": False, "watch": False},
    {"rank": 91, "name": 'Bo Nix', "pos": 'QB', "team": 'DEN', "tier": 5, "flags": [], "target": False, "watch": False},
    {"rank": 92, "name": 'Baker Mayfield', "pos": 'QB', "team": 'TB', "tier": 6, "flags": [], "target": False, "watch": False},
    {"rank": 93, "name": 'C.J. Stroud', "pos": 'QB', "team": 'HOU', "tier": 6, "flags": [], "target": False, "watch": False},
    {"rank": 94, "name": 'Brock Purdy', "pos": 'QB', "team": 'SF', "tier": 6, "flags": [], "target": False, "watch": False},
    {"rank": 95, "name": 'Drake Maye', "pos": 'QB', "team": 'NE', "tier": 3, "flags": [], "target": False, "watch": False},
    {"rank": 96, "name": 'Justin Fields', "pos": 'QB', "team": 'KC', "tier": 6, "flags": ['scheme'], "target": False, "watch": False},
    {"rank": 97, "name": 'Caleb Williams', "pos": 'QB', "team": 'CHI', "tier": 4, "flags": [], "target": False, "watch": False},
    {"rank": 98, "name": 'Trevor Lawrence', "pos": 'QB', "team": 'JAX', "tier": 6, "flags": [], "target": False, "watch": False},
    {"rank": 99, "name": 'Cam Ward', "pos": 'QB', "team": 'TEN', "tier": 6, "flags": [], "target": False, "watch": False},
    {"rank": 100, "name": 'Dak Prescott', "pos": 'QB', "team": 'DAL', "tier": 6, "flags": [], "target": False, "watch": False},
    {"rank": 101, "name": 'Sam Darnold', "pos": 'QB', "team": 'SEA', "tier": 7, "flags": [], "target": False, "watch": False},
    {"rank": 102, "name": 'Matthew Stafford', "pos": 'QB', "team": 'LAR', "tier": 4, "flags": [], "target": False, "watch": False},
    {"rank": 103, "name": 'Tyler Shough', "pos": 'QB', "team": 'NO', "tier": 5, "flags": ['breakout'], "target": False, "watch": False},
    {"rank": 104, "name": 'Colston Loveland', "pos": 'TE', "team": 'CHI', "tier": 4, "flags": [], "target": False, "watch": False, "adp_pick_overall": 108, "adp_round": 11, "adp_slot": 8},
    {"rank": 105, "name": 'Travis Kelce', "pos": 'TE', "team": 'KC', "tier": 6, "flags": ['injury'], "target": False, "watch": False},
    {"rank": 106, "name": 'Mark Andrews', "pos": 'TE', "team": 'BAL', "tier": 6, "flags": [], "target": False, "watch": False},
    {"rank": 107, "name": 'Kyle Pitts Sr.', "pos": 'TE', "team": 'ATL', "tier": 5, "flags": ['breakout'], "target": False, "watch": False, "adp_pick_overall": 118, "adp_round": 12, "adp_slot": 8},
    {"rank": 108, "name": 'Dalton Kincaid', "pos": 'TE', "team": 'BUF', "tier": 7, "flags": [], "target": False, "watch": False},
    {"rank": 109, "name": 'David Njoku', "pos": 'TE', "team": 'CLE', "tier": 7, "flags": [], "target": False, "watch": False},
    {"rank": 110, "name": 'Dallas Goedert', "pos": 'TE', "team": 'PHI', "tier": 6, "flags": [], "target": False, "watch": False},
    {"rank": 111, "name": 'Harold Fannin Jr.', "pos": 'TE', "team": 'CLE', "tier": 6, "flags": ['breakout'], "target": False, "watch": False},
    {"rank": 112, "name": 'T.J. Hockenson', "pos": 'TE', "team": 'MIN', "tier": 7, "flags": [], "target": False, "watch": False},
    {"rank": 113, "name": 'Evan Engram', "pos": 'TE', "team": 'DEN', "tier": 7, "flags": [], "target": False, "watch": False},
    {"rank": 114, "name": 'Jake Ferguson', "pos": 'TE', "team": 'DAL', "tier": 6, "flags": [], "target": False, "watch": False},
    {"rank": 115, "name": 'Cam Skattebo', "pos": 'RB', "team": 'NYG', "tier": 4, "flags": ['injury', 'committee'], "target": False, "watch": False, "adp_pick_overall": 43, "adp_round": 5, "adp_slot": 3, "delta_flag": 'riser', "is_rookie": False},
    {"rank": 116, "name": 'RJ Harvey', "pos": 'RB', "team": 'DEN', "tier": 6, "flags": ['rookie'], "target": False, "watch": False},
    {"rank": 117, "name": 'TreVeyon Henderson', "pos": 'RB', "team": 'NE', "tier": 6, "flags": ['rookie', 'committee'], "target": False, "watch": False, "adp_pick_overall": 49, "adp_round": 5, "adp_slot": 9, "delta_flag": 'riser', "is_rookie": False},
    {"rank": 118, "name": 'Rhamondre Stevenson', "pos": 'RB', "team": 'NE', "tier": 5, "flags": ['committee'], "target": False, "watch": True, "adp_pick_overall": 80, "adp_round": 8, "adp_slot": 10, "delta_flag": 'confirmed', "is_rookie": False},
    {"rank": 120, "name": 'Nick Chubb', "pos": 'RB', "team": 'HOU', "tier": 7, "flags": ['injury'], "target": False, "watch": False},
    {"rank": 121, "name": 'J.K. Dobbins', "pos": 'RB', "team": 'DEN', "tier": 7, "flags": ['injury', 'committee'], "target": False, "watch": False},
    {"rank": 122, "name": 'Kaleb Johnson', "pos": 'RB', "team": 'PIT', "tier": 7, "flags": ['rookie'], "target": False, "watch": False},
    {"rank": 124, "name": 'Matthew Golden', "pos": 'WR', "team": 'GB', "tier": 7, "flags": ['rookie'], "target": False, "watch": False, "adp_pick_overall": 120, "adp_round": 12, "adp_slot": 10, "delta_flag": 'as_expected', "is_rookie": True, "note": 'Rookie'},
    {"rank": 125, "name": 'Denzel Boston', "pos": 'WR', "team": 'SEA', "tier": 7, "flags": ['rookie'], "target": False, "watch": False},
    {"rank": 126, "name": 'Emeka Egbuka', "pos": 'WR', "team": 'TB', "tier": 6, "flags": ['breakout'], "target": False, "watch": False},
    {"rank": 127, "name": 'Tyler Warren', "pos": 'TE', "team": 'IND', "tier": 5, "flags": [], "target": False, "watch": False, "adp_pick_overall": 83, "adp_round": 9, "adp_slot": 3},
    {"rank": 128, "name": 'Broncos D/ST', "pos": 'DST', "team": 'DEN', "tier": 6, "flags": [], "target": False, "watch": False},
    {"rank": 129, "name": 'Seahawks D/ST', "pos": 'DST', "team": 'SEA', "tier": 6, "flags": [], "target": False, "watch": False},
    {"rank": 130, "name": 'Steelers D/ST', "pos": 'DST', "team": 'PIT', "tier": 6, "flags": [], "target": False, "watch": False},
    {"rank": 131, "name": 'Eagles D/ST', "pos": 'DST', "team": 'PHI', "tier": 6, "flags": [], "target": False, "watch": False},
    {"rank": 132, "name": 'Vikings D/ST', "pos": 'DST', "team": 'MIN', "tier": 7, "flags": [], "target": False, "watch": False},
    {"rank": 133, "name": 'Ravens D/ST', "pos": 'DST', "team": 'BAL', "tier": 6, "flags": [], "target": False, "watch": False},
    {"rank": 134, "name": 'Texans D/ST', "pos": 'DST', "team": 'HOU', "tier": 6, "flags": [], "target": False, "watch": False},
    {"rank": 135, "name": 'Bills D/ST', "pos": 'DST', "team": 'BUF', "tier": 7, "flags": [], "target": False, "watch": False},
    {"rank": 136, "name": 'Lions D/ST', "pos": 'DST', "team": 'DET', "tier": 7, "flags": [], "target": False, "watch": False},
    {"rank": 137, "name": 'Rams D/ST', "pos": 'DST', "team": 'LAR', "tier": 6, "flags": [], "target": False, "watch": False},
    {"rank": 138, "name": 'Patriots D/ST', "pos": 'DST', "team": 'NE', "tier": 7, "flags": [], "target": False, "watch": False},
    {"rank": 139, "name": 'Chase McLaughlin', "pos": 'K', "team": 'TB', "tier": 7, "flags": [], "target": False, "watch": False},
    {"rank": 140, "name": 'Cameron Dicker', "pos": 'K', "team": 'LAC', "tier": 7, "flags": [], "target": False, "watch": False},
    {"rank": 141, "name": 'Jake Bates', "pos": 'K', "team": 'DET', "tier": 7, "flags": [], "target": False, "watch": False},
    {"rank": 142, "name": 'Brandon Aubrey', "pos": 'K', "team": 'DAL', "tier": 7, "flags": [], "target": False, "watch": False},
    {"rank": 143, "name": 'Tyler Bass', "pos": 'K', "team": 'BUF', "tier": 7, "flags": [], "target": False, "watch": False},
    {"rank": 144, "name": 'Harrison Butker', "pos": 'K', "team": 'KC', "tier": 7, "flags": [], "target": False, "watch": False},
    {"rank": 145, "name": 'Jake Elliott', "pos": 'K', "team": 'PHI', "tier": 7, "flags": [], "target": False, "watch": False},
    {"rank": 146, "name": 'Wil Lutz', "pos": 'K', "team": 'DEN', "tier": 7, "flags": [], "target": False, "watch": False},
    {"rank": 147, "name": 'Chris Boswell', "pos": 'K', "team": 'PIT', "tier": 7, "flags": [], "target": False, "watch": False},
    {"rank": 148, "name": 'Jeremiyah Love', "pos": 'RB', "team": 'ARI', "tier": 2, "flags": [], "target": False, "watch": False, "adp_pick_overall": 24, "adp_round": 3, "adp_slot": 4, "delta_flag": 'riser', "is_rookie": True, "note": 'Rookie, 3rd overall pick'},
    {"rank": 149, "name": 'Javonte Williams', "pos": 'RB', "team": 'DAL', "tier": 2, "flags": [], "target": False, "watch": False, "adp_pick_overall": 35, "adp_round": 4, "adp_slot": 5, "delta_flag": 'as_expected', "is_rookie": False},
    {"rank": 150, "name": 'DJ Moore', "pos": 'WR', "team": 'CHI', "tier": 3, "flags": [], "target": False, "watch": False, "adp_pick_overall": 56, "adp_round": 6, "adp_slot": 6, "delta_flag": 'faller', "is_rookie": False},
    {"rank": 151, "name": 'Mike Evans', "pos": 'WR', "team": 'SF', "tier": 3, "flags": [], "target": False, "watch": False, "adp_pick_overall": 58, "adp_round": 6, "adp_slot": 8, "delta_flag": 'riser', "is_rookie": False, "note": 'New team (San Francisco) via free agency'},
    {"rank": 152, "name": 'Jadarian Price', "pos": 'RB', "team": 'SEA', "tier": 4, "flags": [], "target": False, "watch": False, "adp_pick_overall": 65, "adp_round": 7, "adp_slot": 5, "delta_flag": 'riser', "is_rookie": True, "note": "Rookie, 1st-round pick (No. 32 overall); role boosted by Charbonnet's ACL tear"},
    {"rank": 153, "name": 'Parker Washington', "pos": 'WR', "team": 'JAX', "tier": 4, "flags": [], "target": False, "watch": False, "adp_pick_overall": 76, "adp_round": 8, "adp_slot": 6, "delta_flag": 'as_expected', "is_rookie": False},
    {"rank": 154, "name": 'Chris Godwin Jr.', "pos": 'WR', "team": 'TB', "tier": 5, "flags": [], "target": False, "watch": False, "adp_pick_overall": 88, "adp_round": 9, "adp_slot": 8, "delta_flag": 'confirmed', "is_rookie": False},
    {"rank": 155, "name": 'Makai Lemon', "pos": 'WR', "team": 'PHI', "tier": 5, "flags": [], "target": False, "watch": False, "adp_pick_overall": 89, "adp_round": 9, "adp_slot": 9, "delta_flag": 'confirmed', "is_rookie": True, "note": 'Rookie, 1st-round pick (No. 20 overall)'},
    {"rank": 156, "name": 'Michael Wilson', "pos": 'WR', "team": 'ARI', "tier": 5, "flags": [], "target": False, "watch": False, "adp_pick_overall": 92, "adp_round": 10, "adp_slot": 2, "delta_flag": 'riser', "is_rookie": False},
    {"rank": 157, "name": 'Quentin Johnston', "pos": 'WR', "team": 'LAC', "tier": 5, "flags": [], "target": False, "watch": False, "adp_pick_overall": 95, "adp_round": 10, "adp_slot": 5, "delta_flag": 'faller', "is_rookie": False},
    {"rank": 158, "name": 'Blake Corum', "pos": 'RB', "team": 'LAR', "tier": 5, "flags": [], "target": False, "watch": False, "adp_pick_overall": 99, "adp_round": 10, "adp_slot": 9, "delta_flag": 'confirmed', "is_rookie": False},
    {"rank": 159, "name": 'Jordan Addison', "pos": 'WR', "team": 'MIN', "tier": 6, "flags": [], "target": False, "watch": False, "adp_pick_overall": 109, "adp_round": 11, "adp_slot": 9, "delta_flag": 'faller', "is_rookie": False},
    {"rank": 160, "name": "Wan'Dale Robinson", "pos": 'WR', "team": 'NYG', "tier": 6, "flags": [], "target": False, "watch": False, "adp_pick_overall": 110, "adp_round": 11, "adp_slot": 10, "delta_flag": 'faller', "is_rookie": False},
    {"rank": 161, "name": 'Jacory Croskey-Merritt', "pos": 'RB', "team": 'WSH', "tier": 6, "flags": [], "target": False, "watch": False, "adp_pick_overall": 118, "adp_round": 12, "adp_slot": 8, "delta_flag": 'confirmed', "is_rookie": False},
    {"rank": 162, "name": 'Jordan Mason', "pos": 'RB', "team": 'MIN', "tier": 7, "flags": [], "target": False, "watch": False, "adp_pick_overall": 122, "adp_round": 13, "adp_slot": 2, "delta_flag": 'confirmed', "is_rookie": False},
    {"rank": 163, "name": 'Romeo Doubs', "pos": 'WR', "team": 'GB', "tier": 7, "flags": [], "target": False, "watch": False, "adp_pick_overall": 123, "adp_round": 13, "adp_slot": 3, "delta_flag": 'as_expected', "is_rookie": False},
    {"rank": 164, "name": 'KC Concepcion', "pos": 'WR', "team": 'CLE', "tier": 7, "flags": [], "target": False, "watch": False, "adp_pick_overall": 124, "adp_round": 13, "adp_slot": 4, "delta_flag": 'as_expected', "is_rookie": True, "note": 'Rookie; team corrected to CLE'},
    {"rank": 165, "name": 'Khalil Shakir', "pos": 'WR', "team": 'BUF', "tier": 7, "flags": [], "target": False, "watch": False, "adp_pick_overall": 130, "adp_round": 13, "adp_slot": 10, "delta_flag": 'confirmed', "is_rookie": False},
    {"rank": 166, "name": 'Woody Marks', "pos": 'RB', "team": 'HOU', "tier": 7, "flags": [], "target": False, "watch": False, "adp_pick_overall": 135, "adp_round": 14, "adp_slot": 5, "delta_flag": 'confirmed', "is_rookie": True, "note": 'Rookie'},
    {"rank": 167, "name": 'Rashid Shaheed', "pos": 'WR', "team": 'NO', "tier": 7, "flags": [], "target": False, "watch": False, "adp_pick_overall": 139, "adp_round": 14, "adp_slot": 9, "delta_flag": 'faller', "is_rookie": False, "note": 'Market disagrees strongly with a believed real WR2 role - could go undrafted in shallower leagues; buy-low candidate if you trust the role'},
    {"rank": 168, "name": 'Tyjae Spears', "pos": 'RB', "team": 'TEN', "tier": 7, "flags": [], "target": False, "watch": False, "adp_pick_overall": 143, "adp_round": 15, "adp_slot": 3, "delta_flag": 'confirmed', "is_rookie": False},
    {"rank": 169, "name": 'Tre Tucker', "pos": 'WR', "team": 'LV', "tier": 7, "flags": [], "target": False, "watch": False, "adp_pick_overall": 157, "adp_round": 16, "adp_slot": 7, "delta_flag": 'confirmed', "is_rookie": False},
]

PLAYBOOK_RULES: list = [
    {
        "title": '1. Cap your transactions',
        "body": "You made 50 moves last season — most in the league by far — and still finished with the fewest total points scored, lower than the 2-11 team. Volume of moves didn't buy production. Set a soft personal limit (say, 2 moves a week) and make yourself justify going past it.",
        "evidence": 'Evidence: season transaction log vs. points-for, all 8 teams.',
    },
    {
        "title": "2. Don't flip a starter off one outlier week",
        "body": "Three different QBs started in your first three weeks (Daniels → Fields → Goff), each swap chasing the previous week's box score. The same thing happened with Wilson/Odunze bouncing between bench and lineup. Week 4 — when Jones settled in and Wilson/Odunze both started together — was your tightest, most predictable week of the year. Stability outperformed chasing.",
        "evidence": 'Evidence: Weeks 1-4 lineup data, QB and WR2/FLEX slots.',
    },
    {
        "title": '3. Watch for the bench-then-pop pattern',
        "body": "Your own read on last season: guys would underperform while started, you'd bench them, and the moment they came out they'd pop off. Before benching a struggling player, check whether the underlying role/target share is actually declining, or if it's just a quiet week. If the role hasn't changed, the points are more likely to still be coming.",
        "evidence": 'Evidence: reported pattern, Wilson/Odunze usage weeks 1-4.',
    },
    {
        "title": '3b. A declining trend is not the same as one bad week',
        "body": 'Etienne is the opposite case from Wilson/Odunze: 16.9 → 11.6 → 8.8 across three straight starts, each one worse than the last, with his best week of the stretch coming on your bench. That\'s a real trend, not a one-off dip. The "don\'t panic on one week" rule only applies to actual one-week outliers — if the score has fallen for 2-3 straight starts, that\'s a role change worth investigating, not noise to ride out.',
        "evidence": 'Evidence: Etienne Weeks 1-5 proj/score.',
    },
    {
        "title": '4. Buy-low trades need proof, not projection',
        "body": 'Egbuka cost a trade after Week 6 and gave nothing back; Collins got traded away right after a concussion, selling low on a healthy long-term asset. Before trading for or away a player mid-season, check the last 3 weeks of actual usage — not the name value or a single bad/good week.',
        "evidence": 'Evidence: in-season trades for Egbuka, Judkins, Pittman, Hall; Collins trade-away.',
    },
    {
        "title": "5. Some injuries just aren't your fault",
        "body": "Hampton's best game of the season (27.5 pts) came the week before he landed on IR. Lamb, Bowers, and Daniels all lost time too. That's real bad luck stacked on a solid draft, not a scouting error — don't over-correct the whole strategy because of one unlucky season.",
        "evidence": 'Evidence: Hampton Wk4 → Wk5 IR; Lamb/Bowers/Daniels missed time.',
    },
    {
        "title": '6. A declining trend while started is different from one bad week',
        "body": "Etienne's scores while started went 16.9 → 11.6 → 8.8 across three straight weeks, with his best game of the stretch coming in the one week he was benched. That's not a slump that snaps back — it's a role quietly shrinking start to start. If a player's production drops each consecutive week he's in your lineup, that's a trend to act on, not a one-off to ride out.",
        "evidence": 'Evidence: Etienne weekly scores, Weeks 1-5.',
    },
    {
        "title": "7. A hot streak isn't a sample size yet",
        "body": "You picked up Juwan Johnson over Dallas Goedert because he'd looked like one of his QB's most trusted targets in a couple of recent games — then he busted the week you started him. The read on Goedert's risk (run-heavy offense, A.J. Brown soaking up targets) was actually correct reasoning. The mistake was treating 2-3 good games as equivalent information to an established, if capped, role. A short hot streak carries more downside than a known boom/bust floor, because you don't have enough data yet to know where the streak settles.",
        "evidence": 'Evidence: Week 5 TE streaming decision, Juwan Johnson vs. Dallas Goedert.',
    },
    {
        "title": '8. A true 50/50 committee hurts both backs, not just one',
        "body": 'Etienne\'s problem in Jacksonville was a single back\'s role quietly eroding while he stayed the nominal starter. Stevenson and Henderson in New England are a different failure mode entirely: neither back ever separated from the other, so both stayed too inconsistent to trust and too capped to have real upside — both spent most of last season on waivers despite real, non-trivial volume. When evaluating a "committee" flag, ask which version it is: a clear lead back with a handcuff (fine to draft the lead), or a genuine even split (risky for anyone involved, no matter who looks like the nominal starter on paper).',
        "evidence": 'Evidence: Rhamondre Stevenson / TreVeyon Henderson 2025 season, New England backfield.',
    },
    {
        "title": "9. Don't stack two health-risk TEs — production risk is a different category",
        "body": 'Two practice drafts landed on the same pattern by accident: both TE picks (Kittle + Kraft) were simultaneous health bets — real risk of missed games at the same position, with no fallback if either recovery ran slow. That\'s the specific thing to avoid. It\'s a different situation than pairing a health-risk TE with one who\'s simply inconsistent week to week (like Goedert, whose risk is TD/target variance, not availability) — that\'s one real bet plus one known, if boom-or-bust, floor, which is a defensible pairing. The rule is about not doubling up on "might not play," not about avoiding every TE with any flag next to his name.',
        "evidence": 'Evidence: Practice Drafts 1 and 5 (Kittle + Kraft, both health risk) vs. Practice Draft 7 (Kittle + Goedert, one health risk + one production-variance).',
    },
    {
        "title": 'Draft Shape: Round-by-Round Plan',
        "body": 'Target end roster: ~5 RB, ~6 WR, 2 QB, 2 TE, 1 D/ST, 1 K (16 rounds, 9 starters + 7 bench).',
        "evidence": 'Evidence: 2025 roster construction (16 total picks) vs. in-season RB scarcity and IR usage.',
    },
]
